
app:
  name: prjsync
  email: molinari@incode.it
  host: http://prjsync.herokuapp.com/

integrations:
  basecamp:
    account_id: "3104769"
    api_client_id: <%= ENV["BASECAMP_CLIENT_ID"] %>
    api_client_secret: <%= ENV["BASECAMP_CLIENT_SECRET"] %>
    oauth_url_base: https://launchpad.37signals.com
    oauth_path_callback: /oauth2/callback/basecamp
    oauth_path_authorize: /authorization/new?type=web_server
    oauth_path_token: /authorization/token?type=web_server
